// Benny Study · Cloud Center v2
(function(){
  const NOTION_LIBRARY_URL='https://app.notion.com/p/3b074307ccb88187b750e19705c9b756';
  const REQUIRED=['courses','plan','errors','weekly','examNotes','settings','training','meta'];
  function counts(){return{courses:state.courses?.length||0,plan:state.plan?.length||0,errors:state.errors?.length||0,weekly:state.weekly?.length||0,training:state.training?.history?.length||0,exams:Object.keys(state.examNotes||{}).length};}
  function validate(){const missing=REQUIRED.filter(k=>!(k in state));const badTraining=!state.training||!Array.isArray(state.training.history);return{ok:!missing.length&&!badTraining,missing,badTraining,counts:counts()};}
  function todaySummary(){const today=dateISO(new Date());const done=(state.courses||[]).filter(x=>x.done).length;const sessions=(state.training?.history||[]).filter(x=>String(x.date||'').startsWith(today));const questions=sessions.reduce((s,x)=>s+Number(x.total||0),0);const correct=sessions.reduce((s,x)=>s+Number(x.correct||0),0);const errors=(state.errors||[]).filter(x=>x.date===today).length;return{today,done,sessions:sessions.length,questions,accuracy:questions?Math.round(correct/questions*100):0,errors};}
  function downloadText(text,name,type='text/markdown'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);}
  function notionMarkdown(){const x=todaySummary();const recent=(state.training?.history||[]).slice(-5).reverse();return `# Daily Review · ${x.today}\n\n## 今日数据\n- 课程累计完成：${x.done}\n- 训练次数：${x.sessions}\n- 训练题量：${x.questions}\n- 平均正确率：${x.accuracy}%\n- 新增错题：${x.errors}\n\n## 最近训练\n${recent.length?recent.map(r=>`- ${r.title||r.type||'专项训练'}：${r.correct||0}/${r.total||0}，${r.accuracy||0}% ，平均 ${r.avgSeconds||0} 秒/题`).join('\n'):'- 暂无训练记录'}\n\n## 今日总结\n- 做得好的：\n- 需要调整的：\n- 明日重点：\n`;}
  function enhanceDialog(){const card=document.querySelector('#settingsDialog .dialog-card');if(!card||card.querySelector('.cloud-v2-panel'))return;const v=validate(),c=v.counts;card.insertAdjacentHTML('beforeend',`<section class="cloud-v2-panel"><div class="cloud-v2-head"><div><span>☁️ Cloud Center v2</span><strong>${v.ok?'数据结构完整':'需要检查'}</strong></div><button class="secondary" id="cloudIntegrityCheck" type="button">完整性检查</button></div><div class="cloud-counts"><span>课程 <b>${c.courses}</b></span><span>计划 <b>${c.plan}</b></span><span>错题 <b>${c.errors}</b></span><span>训练 <b>${c.training}</b></span><span>周复盘 <b>${c.weekly}</b></span><span>考试 <b>${c.exams}</b></span></div><div class="notion-bridge"><div><span>📖 Growth Library</span><small>Notion 已建立 Daily Review、Weekly Review 与 Training Archive。</small></div><div><a class="secondary notion-open" href="${NOTION_LIBRARY_URL}" target="_blank" rel="noreferrer">打开 Notion</a><button class="secondary" id="exportNotionSummary" type="button">导出今日摘要</button></div></div><p class="cloud-v2-note">GitHub 保存完整原始数据；Notion 用于阅读与复盘。当前网页采用安全的“摘要导出桥”，不在浏览器内保存 Notion 密钥。</p></section>`);document.getElementById('cloudIntegrityCheck')?.addEventListener('click',()=>{const r=validate();cloudStatus.textContent=r.ok?'检查通过：课程、计划、错题、训练、复盘和考试数据均会进入完整云存档。':`发现问题：${r.missing.join('、')||'训练历史结构异常'}`;});document.getElementById('exportNotionSummary')?.addEventListener('click',()=>downloadText(notionMarkdown(),`Benny-Daily-Review-${dateISO(new Date())}.md`));}
  const oldOpen=window.openSettings||openSettings;window.openSettings=function(){oldOpen();setTimeout(enhanceDialog,0);};
  const oldPush=window.pushCloud||pushCloud;window.pushCloud=async function(){state.meta||={};state.meta.schemaVersion=2;state.meta.lastCloudBackupAt=new Date().toISOString();state.meta.backupIncludes=REQUIRED;saveState();return oldPush();};
  document.getElementById('settingsButton')?.addEventListener('click',()=>setTimeout(enhanceDialog,0));
})();