// Benny Study · Portable Export Center
(function(){
  function stamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);}
  function download(content,name,type){const blob=new Blob(['\ufeff',content],{type:type||'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
  function categoryName(v){return({arithmetic:'计算能力',reasoning:'数字推理',thinking:'思维能力',data:'资料分析专项'})[v]||v||'未分类';}
  function allTrainingRows(){const rows=[];(state.training?.history||[]).forEach((session,si)=>{const answers=Array.isArray(session.answers)?session.answers:[];if(!answers.length){rows.push({sessionIndex:si+1,sessionId:session.id||'',date:session.date||'',category:categoryName(session.category),title:session.title||session.type||'',questionIndex:'',question:'',userAnswer:'',answer:'',correct:'',timeMs:'',timeSeconds:'',sessionAccuracy:session.accuracy??'',sessionDuration:session.durationSeconds??''});return;}answers.forEach((q,qi)=>rows.push({sessionIndex:si+1,sessionId:session.id||'',date:session.date||'',category:categoryName(session.category),title:session.title||session.type||'',questionIndex:qi+1,question:q.question||q.text||'',userAnswer:q.userAnswer??'',answer:q.answer??'',correct:q.correct===true?'正确':q.correct===false?'错误':'',timeMs:q.timeMs??'',timeSeconds:q.timeMs!=null?(Number(q.timeMs)/1000).toFixed(3):(q.timeSeconds??''),sessionAccuracy:session.accuracy??'',sessionDuration:session.durationSeconds??''}));});return rows;}
  function exportJson(){const pack={format:'Benny Study Portable Archive',schemaVersion:3,exportedAt:new Date().toISOString(),instructions:'保留原始字段。可交给任意支持 JSON 的 AI、表格工具或脚本分析。',data:state};download(JSON.stringify(pack,null,2),`Benny-Study-Full-Archive-${stamp()}.json`,'application/json;charset=utf-8');}
  function exportCsv(){const rows=allTrainingRows();const headers=['场次序号','场次ID','日期','分区','专项','题号','题目','你的答案','正确答案','结果','耗时毫秒','耗时秒','场次正确率','场次总耗时秒'];const keys=['sessionIndex','sessionId','date','category','title','questionIndex','question','userAnswer','answer','correct','timeMs','timeSeconds','sessionAccuracy','sessionDuration'];const text=[headers.join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\n');download(text,`Benny-Training-Question-Details-${stamp()}.csv`,'text/csv;charset=utf-8');}
  function overall(){const h=state.training?.history||[];const total=h.reduce((s,x)=>s+Number(x.total||0),0);const correct=h.reduce((s,x)=>s+Number(x.correct||0),0);const timed=allTrainingRows().filter(x=>Number(x.timeMs)>0);const avg=timed.length?timed.reduce((s,x)=>s+Number(x.timeMs),0)/timed.length/1000:0;return{sessions:h.length,total,correct,accuracy:total?Math.round(correct/total*100):0,avg:Number(avg.toFixed(2))};}
  function markdown(){const o=overall();const courses=state.courses||[], plan=state.plan||[], errors=state.errors||[], weekly=state.weekly||[], exams=state.examNotes||{}, history=state.training?.history||[];const done=courses.filter(x=>x.done).length;const recent=history.slice(-20).reverse();let md=`# Benny Study · AI 分析数据包\n\n> 导出时间：${new Date().toLocaleString()}\n> 用途：可直接上传给任意 AI，请基于原始记录分析学习进度、速度、正确率、薄弱项与下一步安排。\n\n## 建议给 AI 的任务\n\n1. 先检查数据是否完整，不要猜测缺失字段。\n2. 分析课程进度、错题结构、训练正确率与每题耗时。\n3. 找出“正确但过慢”“速度快但错误率高”“反复出错”的专项。\n4. 给出未来 7 天可执行建议，并说明依据。\n5. 不要修改原始记录。\n\n## 总览\n\n- 课程总数：${courses.length}\n- 已完成课程：${done}\n- 每日计划天数：${plan.length}\n- 错题数量：${errors.length}\n- 周复盘数量：${weekly.length}\n- 考试记录数量：${Object.keys(exams).length}\n- 训练场次：${o.sessions}\n- 训练总题量：${o.total}\n- 训练总正确率：${o.accuracy}%\n- 有逐题计时记录的平均耗时：${o.avg} 秒/题\n\n## 最近训练记录\n\n`;
  if(!recent.length) md+='暂无训练记录。\n';
  recent.forEach((r,i)=>{const answers=Array.isArray(r.answers)?r.answers:[];const times=answers.map(x=>Number(x.timeMs||0)).filter(Boolean);const avg=times.length?(times.reduce((a,b)=>a+b,0)/times.length/1000).toFixed(2):(r.avgSeconds??'无');md+=`### ${i+1}. ${r.title||r.type||'专项训练'}\n\n- 日期：${r.date||'未知'}\n- 分区：${categoryName(r.category)}\n- 成绩：${r.correct||0}/${r.total||0}\n- 正确率：${r.accuracy||0}%\n- 总耗时：${r.durationSeconds||0} 秒\n- 平均每题：${avg} 秒\n`;
    if(answers.length){md+='\n| 题号 | 题目 | 我的答案 | 正确答案 | 结果 | 耗时 |\n|---:|---|---:|---:|---|---:|\n';answers.forEach((q,qi)=>{const sec=q.timeMs!=null?`${(Number(q.timeMs)/1000).toFixed(2)} 秒`:'未记录';md+=`| ${qi+1} | ${String(q.question||q.text||'').replace(/\|/g,'\\|')} | ${q.userAnswer??''} | ${q.answer??''} | ${q.correct?'正确':'错误'} | ${sec} |\n`;});}
    md+='\n';
  });
  md+='## 错题记录\n\n';if(!errors.length)md+='暂无错题。\n';else errors.forEach((e,i)=>{md+=`${i+1}. ${e.date||''}｜${e.subject||''}｜${e.chapter||e.module||''}｜${e.type||''}\n   - 错误原因：${e.reason||'未填写'}\n   - 正确方法：${e.method||'未填写'}\n   - 状态：${e.status||'未填写'}\n`;});
  md+='\n## 周复盘\n\n';if(!weekly.length)md+='暂无周复盘。\n';else weekly.slice(-12).reverse().forEach((w,i)=>{md+=`${i+1}. ${w.week||w.date||w.startDate||'未标日期'}：${w.summary||w.note||JSON.stringify(w)}\n`;});
  md+='\n## 数据说明\n\n- 完整原始数据请同时参考同一时间导出的 JSON 文件。\n- 旧训练记录可能只有场次总耗时，没有逐题耗时。\n- `timeMs` 为单题从展示到提交的耗时，单位为毫秒。\n';return md;}
  function exportMarkdown(){download(markdown(),`Benny-Study-AI-Analysis-Package-${stamp()}.md`,'text/markdown;charset=utf-8');}
  function insertPanel(){const card=document.querySelector('#settingsDialog .dialog-card');if(!card||card.querySelector('.portable-export-panel'))return;card.insertAdjacentHTML('beforeend',`<section class="portable-export-panel"><div class="portable-export-title"><div><span>📦 独立导出中心</span><strong>不依赖 GitHub 或 Notion</strong></div></div><p>把记录下载到本地后，可以直接上传给其他 AI、表格软件或数据分析工具。</p><div class="portable-export-grid"><button type="button" class="portable-export-button" id="exportPortableJson"><b>原始数据 JSON</b><small>完整存档，可恢复、可编程分析</small></button><button type="button" class="portable-export-button" id="exportPortableMarkdown"><b>AI 分析包 Markdown</b><small>带说明、汇总和逐题明细，可直接上传</small></button><button type="button" class="portable-export-button" id="exportPortableCsv"><b>训练逐题 CSV</b><small>每道题的答案、对错和耗时</small></button></div><p class="portable-export-tip">建议同时保存 JSON 和 Markdown：JSON 负责完整，Markdown 负责让 AI 快速读懂。</p></section>`);document.getElementById('exportPortableJson')?.addEventListener('click',exportJson);document.getElementById('exportPortableMarkdown')?.addEventListener('click',exportMarkdown);document.getElementById('exportPortableCsv')?.addEventListener('click',exportCsv);}
  const btn=document.getElementById('settingsButton');btn?.addEventListener('click',()=>setTimeout(insertPanel,0));
  const previousOpen=window.openSettings; if(typeof previousOpen==='function'){window.openSettings=function(){previousOpen();setTimeout(insertPanel,0);};}
  window.BennyPortableExport={exportJson,exportMarkdown,exportCsv};
})();
